framework:
    notifier:
        chatter_transports:
        texter_transports:
            fakesms+email: '%env(FAKE_SMS_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
